### ISSUE TITLE
小兄弟,用法或者demo有了吗

### ISSUE THREAD

**Issue by Geek-ch** [Dawninest/react-native-ftp-iOS#1]

**Comment by Dawninest** [comment]
竟然真的有人要，不方，我尽快做一个

**Comment by Geek-ch** [comment]
@Dawninest  刚好公司要用ftp上传, 可惜你这边只是iOS的, 没有看到有兼容两端的库

**Comment by Dawninest** [comment]
OK,更新了一下Demo及文档，如果对你有帮助的话请 star ,
实际使用中有什么问题也可以继续问我

**Comment by Geek-ch** [comment]
@Dawninest  更新的很快,相当给力. 不过我接入以后,尝试了一下,传入地址后就崩了,帮忙看下是啥原因.

`
            const ftpTask = {
                ftpServerIp: '192.168.xxx.xx', //链接的FTP服务器IP
                username: 'xx', //登录FTP服务器的账户
                password: 'xxx', //登录FTP服务器的密码
                ftpServerPort: 21, //FTP服务器端口
                fileMimeType: 'image', // other image audio 三种类型选一个
                isUpload: true, //上传 - true 下载 - false
                localPath: "/Users/he/Library/Developer/CoreSimulator/Devices/3700D11C-0C48-4251-88A0-F4C910593F16/data/Containers/Data/Application/69145BBD-C052-46B2-9610-700774570ECE/tmp/react-native-image-crop-picker/D75346E8-3C1E-4210-9B66-704DA4949826.jpg",//(本地文件的绝对路径) file:///开头
                remoteFilePath: '/p7/', //(绝对路径) ，上传时提供文件夹地址，后带 "/" eg /2016-11-11-1/，下载时提供文件地址(2016-11-11-1/down)
                toAccount: '文件发送对象',// 与FTP传输无关，能在传输监听中拿到，方便后续逻辑处理
                transferId: '23333333xxx',// 与FTP传输无关，能在传输监听中拿到，方便后续逻辑处理
                fileSize: '233333', // 与FTP传输无关，能在传输监听中拿到，方便后续逻辑处理
                isSSL:false
            };
            NativeModules.FileTransfer.addFtpTask(ftpTask)
`

我是这样调用的, 一旦调用会报错,然后崩了.

> libc++abi.dylib:  terminating with uncaught exception of type NSException

**Comment by Geek-ch** [comment]
const ftpTask = {
                ftpServerIp: '192.168.xxx.xx', //链接的FTP服务器IP
                username: 'xx', //登录FTP服务器的账户
                password: 'xxx', //登录FTP服务器的密码
                ftpServerPort: 21, //FTP服务器端口
                fileMimeType: 'image', // other image audio 三种类型选一个
                isUpload: true, //上传 - true 下载 - false
                localPath: "/Users/he/Library/Developer/CoreSimulator/Devices/3700D11C-0C48-4251-88A0-F4C910593F16/data/Containers/Data/Application/69145BBD-C052-46B2-9610-700774570ECE/tmp/react-native-image-crop-picker/D75346E8-3C1E-4210-9B66-704DA4949826.jpg",//(本地文件的绝对路径) file:///开头
                remoteFilePath: '/p7/', //(绝对路径) ，上传时提供文件夹地址，后带 "/" eg /2016-11-11-1/，下载时提供文件地址(2016-11-11-1/down)
                toAccount: '文件发送对象',// 与FTP传输无关，能在传输监听中拿到，方便后续逻辑处理
                transferId: '23333333xxx',// 与FTP传输无关，能在传输监听中拿到，方便后续逻辑处理
                fileSize: '233333', // 与FTP传输无关，能在传输监听中拿到，方便后续逻辑处理
                //isSSL: SimConfig.getSimConfig("isFtpSSL"), // iOS不支持ssl ，无用参数，方便与安卓版统一接口
                isSSL:false
            };
            NativeModules.FileTransfer.addFtpTask(ftpTask)

**Comment by Geek-ch** [comment]
我断点调试了下, 发现 fileSize: '233333', 改为 fileSize: 233333,  就不会报错,估计是NSInteger的缘故

**Comment by Dawninest** [comment]
哇，两点过还在调呢，可真是勤勉啊，
不好意思啊，确实是我的疏忽写错了，给你添麻烦了，
话说这个问题处理后后续还遇到了什么问题不？

**Comment by Geek-ch** [comment]
@Dawninest  没办法, 进度赶着呢.  你已经弄很棒了.
我能传上去了,但是文件传输异常 
error:"Server aborted transfer."  
在ftp上面没有字节大小,打开显示 因存在错误而无法显示.

设置文件名是设置 'transferId'这个值吗,我看代码是备注' 发送文件的uuid 32位', 但是发送这个数字后,文件就没法显示jpg或者png了,这个怎么处理

**Comment by Geek-ch** [comment]
fileMimeType:"image"
fileSize:43664
ftpServerIp:"192.168.xxx.xx"
ftpServerPort:21
isSSL:false
isUpload:true
localPath:"/Users/he/Library/Developer/CoreSimulator/Devices/3700D11C-0C48-4251-88A0-F4C910593F16/data/Containers/Data/Application/69145BBD-C052-46B2-9610-700774570ECE/tmp/react-native-image-crop-picker/D75346E8-3C1E-4210-9B66-704DA4949826.jpg"
password:"xxxx"
remoteFilePath:"/app/21004251"
toAccount:21004251
transferId:"B84E8479475C4727A4A4"
username:"xxx"

传输的数据是这些

**Comment by Dawninest** [comment]
上传这个文件名，会在那个地址后面拼 transferId ，这个之前做的时候是公司需求这么写的，如果你不想这么用的话，把 FileTransfer.m 里面 150 行的 那个if 去掉，并把你的 remoteFilePath 后面加上你打算存在服务器上名字，( remoteFilePath:"/app/21004251/xxxx.jpg")

**Comment by Dawninest** [comment]
然后这个 error:"Server aborted transfer." 报错的话，如果 在ftp上面没有字节大小，说明是这个文件在服务器上创建成功，但是传输过程出了问题。
看看在 371 行的异常收集是怎么打印的，然后在 293行 和 305 行打断点，这种情况的应该会进 293行，但是不会进 305 行，
总之你把那个 371  行异常打印发我看看

**Comment by Geek-ch** [comment]
这样沟通有点慢...方便加下我吗 851921369 , thx

**Comment by Geek-ch** [comment]
这个bug解决了,  作者@Dawninest  人超好,陪着配置了大半天.

总结下几个问题,可以close了.
1 . iOS的图片地址记得加上 'file://' ,不然会读不到正确路径.
2 . fileSize要用int的形式
3 . 如果有无限检测:文件传输的进度跟踪,需要在FileTransfer.m的305行将最小值改为0.1, 

> if(percent >= 0.1 && percent < 1) {
